bt = {
    "st": True,
    "statusCode": 200,
    "data": [
        {
            "id": 1,
            "name": "pen00001",
            "term": "asdsddsadsd",
            "isDelete": False,
            "createAt": "2025-07-11T11:32:27.589Z",
            "createdBy": 2,
            "updateAt": "2025-07-11T11:43:18.716Z",
            "updateBy": 2
        }
    ],
    "total_rows": 1,
    "total_pages": 1
}

billterm = bt
purch = {
    "st": True,
    "statusCode": 200,
    "data": [
        {
            "id": 20,
            "invoiceType": "ITEM",
            "voucherId": 2,
            "invoiceNo": "PR-5",
            "invoiceDate": "27-06-2025",
            "ledgerId": 17,
            "billToId": 17,
            "billToName": "Dddsdss",
            "billToAddress": "507,sun gravitas ,Ahmedabad",
            "billToCountry": "India",
            "billToState": "Andaman and Nicobar Islands",
            "billToCity": "Port Blair",
            "billToPincode": "564651",
            "billTogstNumber": None,
            "brokerId": None,
            "brokerage": None,
            "shipToId": 17,
            "shipToName": "Dddsdss",
            "shipToAddress": "507,sun gravitas ,Ahmedabad",
            "shipToCountry": "India",
            "shipToState": "Andaman and Nicobar Islands",
            "shipToCity": "Port Blair",
            "shipToPincode": "564651",
            "shipTogstNumber": "",
            "transportId": None,
            "transportMode": None,
            "vehicleNo": "",
            "narration": "",
            "referenceNo": "",
            "lrNo": "",
            "lrDate": "",
            "dueDays": None,
            "dueDate": "",
            "portOfLoading": None,
            "portOfDischarge": None,
            "shippingBillNo": None,
            "shippingDate": None,
            "portCode": None,
            "currencyCode": "INR",
            "currencyRate": "1",
            "taxableAmount": "0",
            "igstLedgerId": 2,
            "igstAmount": "0",
            "cgstLedgerId": 6,
            "cgstAmount": "0",
            "sgstLedgerId": 4,
            "sgstAmount": "0",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "0",
            "taxability": "EXEMPT",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "",
            "attachment": None,
            "reference": None,
            "outstanding": "0",
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-07-15T05:10:02.576Z",
            "createBy": 2,
            "updateAt": "2025-07-15T05:11:35.801Z",
            "updateBy": 2,
            "items": [
                {
                    "id": 1,
                    "purchaseId": 20,
                    "invoiceDate": "2025-06-27T00:00:00.000Z",
                    "taxableType": "NILL",
                    "itemId": 1,
                    "warehouseId": None,
                    "batchNo": None,
                    "hsn": None,
                    "altUom": "LTR",
                    "altQty": 1,
                    "uom": "LTR",
                    "qty": 1,
                    "remainQty": 1,
                    "rateType": None,
                    "rate": "0",
                    "total": "0",
                    "igst": "0",
                    "igstAmount": "0",
                    "sgst": "0",
                    "sgstAmount": "0",
                    "cgst": "0",
                    "cgstAmount": "0",
                    "cess": "0",
                    "cessAmount": "0",
                    "discount": "0",
                    "discountAmount": "0",
                    "discountType": "PERCENTAGE",
                    "isInvoiceDiscount": False,
                    "invoiceDiscount": "1",
                    "invoiceDiscountAmount": "0",
                    "taxableAmount": "0",
                    "remark": "",
                    "receiptNoteId": None,
                    "isExpense": False,
                    "isAdditional": False,
                    "isCancel": True,
                    "isDelete": False,
                    "createAt": "2025-06-26T09:45:25.168Z",
                    "createBy": 7,
                    "updateAt": "2025-07-15T05:11:35.807Z",
                    "updateBy": 2
                }
            ]
        },
        {
            "id": 18,
            "invoiceType": "ITEM",
            "voucherId": 2,
            "invoiceNo": "PR-4",
            "invoiceDate": "27-06-2025",
            "ledgerId": 17,
            "billToId": 17,
            "billToName": "Dddsdss",
            "billToAddress": "507,sun gravitas ,Ahmedabad",
            "billToCountry": "India",
            "billToState": "Andaman and Nicobar Islands",
            "billToCity": "Port Blair",
            "billToPincode": "564651",
            "billTogstNumber": None,
            "brokerId": None,
            "brokerage": None,
            "shipToId": 17,
            "shipToName": "Dddsdss",
            "shipToAddress": "507,sun gravitas ,Ahmedabad",
            "shipToCountry": "India",
            "shipToState": "Andaman and Nicobar Islands",
            "shipToCity": "Port Blair",
            "shipToPincode": "564651",
            "shipTogstNumber": "",
            "transportId": None,
            "transportMode": None,
            "vehicleNo": "",
            "narration": "",
            "referenceNo": "",
            "lrNo": "",
            "lrDate": "",
            "dueDays": None,
            "dueDate": "",
            "portOfLoading": None,
            "portOfDischarge": None,
            "shippingBillNo": None,
            "shippingDate": None,
            "portCode": None,
            "currencyCode": "INR",
            "currencyRate": "1",
            "taxableAmount": "0",
            "igstLedgerId": 2,
            "igstAmount": "0",
            "cgstLedgerId": 6,
            "cgstAmount": "0",
            "sgstLedgerId": 4,
            "sgstAmount": "0",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "0",
            "taxability": "EXEMPT",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "",
            "attachment": None,
            "reference": None,
            "outstanding": "0",
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-07-09T11:03:09.090Z",
            "createBy": 1,
            "updateAt": "2025-07-09T11:07:13.117Z",
            "updateBy": 1,
            "items": []
        },
        {
            "id": 17,
            "invoiceType": "ITEM",
            "voucherId": 2,
            "invoiceNo": "PR-3",
            "invoiceDate": "27-06-2025",
            "ledgerId": 17,
            "billToId": 17,
            "billToName": "Dddsdss",
            "billToAddress": "507,sun gravitas ,Ahmedabad",
            "billToCountry": "India",
            "billToState": "Andaman and Nicobar Islands",
            "billToCity": "Port Blair",
            "billToPincode": "564651",
            "billTogstNumber": None,
            "brokerId": None,
            "brokerage": None,
            "shipToId": 17,
            "shipToName": "Dddsdss",
            "shipToAddress": "507,sun gravitas ,Ahmedabad",
            "shipToCountry": "India",
            "shipToState": "Andaman and Nicobar Islands",
            "shipToCity": "Port Blair",
            "shipToPincode": "564651",
            "shipTogstNumber": "",
            "transportId": None,
            "transportMode": None,
            "vehicleNo": "",
            "narration": "",
            "referenceNo": "",
            "lrNo": "",
            "lrDate": "",
            "dueDays": None,
            "dueDate": "",
            "portOfLoading": None,
            "portOfDischarge": None,
            "shippingBillNo": None,
            "shippingDate": None,
            "portCode": None,
            "currencyCode": "INR",
            "currencyRate": "111",
            "taxableAmount": "0",
            "igstLedgerId": 2,
            "igstAmount": "0",
            "cgstLedgerId": 6,
            "cgstAmount": "0",
            "sgstLedgerId": 4,
            "sgstAmount": "0",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "0",
            "taxability": "EXEMPT",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "",
            "attachment": None,
            "reference": None,
            "outstanding": "0",
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-07-09T10:12:32.234Z",
            "createBy": 1,
            "updateAt": "2025-07-14T12:50:59.951Z",
            "updateBy": 2,
            "items": []
        },
        {
            "id": 16,
            "invoiceType": "ITEM",
            "voucherId": 2,
            "invoiceNo": "PR-2",
            "invoiceDate": "27-06-2025",
            "ledgerId": 17,
            "billToId": 17,
            "billToName": "Dddsdss",
            "billToAddress": "507,sun gravitas ,Ahmedabad",
            "billToCountry": "India",
            "billToState": "Andaman and Nicobar Islands",
            "billToCity": "Port Blair",
            "billToPincode": "564651",
            "billTogstNumber": None,
            "brokerId": None,
            "brokerage": None,
            "shipToId": 17,
            "shipToName": "Dddsdss",
            "shipToAddress": "507,sun gravitas ,Ahmedabad",
            "shipToCountry": "India",
            "shipToState": "Andaman and Nicobar Islands",
            "shipToCity": "Port Blair",
            "shipToPincode": "564651",
            "shipTogstNumber": "",
            "transportId": None,
            "transportMode": None,
            "vehicleNo": "",
            "narration": "",
            "referenceNo": "",
            "lrNo": "",
            "lrDate": "",
            "dueDays": None,
            "dueDate": "",
            "portOfLoading": None,
            "portOfDischarge": None,
            "shippingBillNo": None,
            "shippingDate": None,
            "portCode": None,
            "currencyCode": "",
            "currencyRate": "1",
            "taxableAmount": "0",
            "igstLedgerId": 2,
            "igstAmount": "0",
            "cgstLedgerId": 6,
            "cgstAmount": "0",
            "sgstLedgerId": 4,
            "sgstAmount": "0",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "0",
            "taxability": "EXEMPT",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "",
            "attachment": None,
            "reference": None,
            "outstanding": "0",
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-07-09T09:12:28.994Z",
            "createBy": 1,
            "updateAt": "2025-07-09T09:12:28.994Z",
            "updateBy": 0,
            "items": [
                {
                    "id": 12,
                    "purchaseId": 16,
                    "invoiceDate": "2025-06-27T00:00:00.000Z",
                    "taxableType": "NILL",
                    "itemId": 1,
                    "warehouseId": None,
                    "batchNo": None,
                    "hsn": None,
                    "altUom": "LTR",
                    "altQty": 1,
                    "uom": "LTR",
                    "qty": 1,
                    "remainQty": 0,
                    "rateType": None,
                    "rate": "0",
                    "total": "0",
                    "igst": "0",
                    "igstAmount": "0",
                    "sgst": "0",
                    "sgstAmount": "0",
                    "cgst": "0",
                    "cgstAmount": "0",
                    "cess": "0",
                    "cessAmount": "0",
                    "discount": "0",
                    "discountAmount": "0",
                    "discountType": "PERCENTAGE",
                    "isInvoiceDiscount": False,
                    "invoiceDiscount": "1",
                    "invoiceDiscountAmount": "0",
                    "taxableAmount": "0",
                    "remark": "",
                    "receiptNoteId": None,
                    "isExpense": False,
                    "isAdditional": False,
                    "isCancel": False,
                    "isDelete": False,
                    "createAt": "2025-07-09T09:12:29.004Z",
                    "createBy": 1,
                    "updateAt": "2025-07-09T09:12:29.004Z",
                    "updateBy": 0
                }
            ]
        },
        {
            "id": 4,
            "invoiceType": "ITEM",
            "voucherId": 9,
            "invoiceNo": "SO-1",
            "invoiceDate": "11-04-2023",
            "ledgerId": 17,
            "billToId": 17,
            "billToName": "KRISHNA AGENCY",
            "billToAddress": "sachin char rasta, surat",
            "billToCountry": "India",
            "billToState": "Gujarat",
            "billToCity": "Navsari",
            "billToPincode": "395007",
            "billTogstNumber": None,
            "brokerId": None,
            "brokerage": None,
            "shipToId": 17,
            "shipToName": "KRISHNA AGENCY",
            "shipToAddress": "sachin char rasta, surat",
            "shipToCountry": "India",
            "shipToState": "Gujarat",
            "shipToCity": "Navsari",
            "shipToPincode": "395007",
            "shipTogstNumber": "24HEEPS7046D1ZE",
            "transportId": None,
            "transportMode": "ROAD",
            "vehicleNo": "GJ-21-BA-2164",
            "narration": "",
            "referenceNo": None,
            "lrNo": "427TR3284T239",
            "lrDate": "24-06-2024",
            "dueDays": None,
            "dueDate": "",
            "portOfLoading": None,
            "portOfDischarge": None,
            "shippingBillNo": None,
            "shippingDate": None,
            "portCode": None,
            "currencyCode": "INR",
            "currencyRate": "1",
            "taxableAmount": "58408.21",
            "igstLedgerId": 2,
            "igstAmount": "0",
            "cgstLedgerId": 6,
            "cgstAmount": "0",
            "sgstLedgerId": 4,
            "sgstAmount": "0",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "58408.21",
            "taxability": "TAXABLE",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "",
            "attachment": None,
            "reference": None,
            "outstanding": "-50591.79",
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-06-26T09:45:25.166Z",
            "createBy": 7,
            "updateAt": "2025-06-30T12:42:13.465Z",
            "updateBy": 1,
            "items": [
                {
                    "id": 2,
                    "purchaseId": 4,
                    "invoiceDate": "2023-04-11T00:00:00.000Z",
                    "taxableType": "TAXABLE",
                    "itemId": 37,
                    "warehouseId": None,
                    "batchNo": None,
                    "hsn": "",
                    "altUom": None,
                    "altQty": 10,
                    "uom": None,
                    "qty": 10,
                    "remainQty": 10,
                    "rateType": "PERCENTAGE",
                    "rate": "3",
                    "total": "1701.21",
                    "igst": "12",
                    "igstAmount": "0",
                    "sgst": "6",
                    "sgstAmount": "0",
                    "cgst": "6",
                    "cgstAmount": "0",
                    "cess": "0",
                    "cessAmount": "0",
                    "discount": "0",
                    "discountAmount": "0",
                    "discountType": None,
                    "isInvoiceDiscount": False,
                    "invoiceDiscount": "0",
                    "invoiceDiscountAmount": "0",
                    "taxableAmount": "1701.21",
                    "remark": "",
                    "receiptNoteId": None,
                    "isExpense": True,
                    "isAdditional": True,
                    "isCancel": True,
                    "isDelete": False,
                    "createAt": "2025-06-26T09:45:25.174Z",
                    "createBy": 7,
                    "updateAt": "2025-06-30T09:20:49.659Z",
                    "updateBy": 1
                }
            ]
        }
    ],
    "total_rows": 5,
    "total_pages": 1
}
get_purch = purch
sale = {
    "st": True,
    "statusCode": 200,
    "data": [
        {
            "id": 14,
            "invoiceType": "ITEM",
            "voucherId": 1,
            "invoiceNo": "SL-3",
            "invoiceDate": "10-07-2025",
            "ledgerId": 15,
            "billToId": 18,
            "billToName": "Account",
            "billToAddress": "507,sun gravitas ,Ahmedabad",
            "billToCountry": "India",
            "billToState": "Dadra and Nagar Haveli",
            "billToCity": "Silvassa",
            "billToPincode": "564651",
            "billTogstNumber": None,
            "brokerId": None,
            "brokerage": None,
            "shipToId": 18,
            "shipToName": "Account",
            "shipToAddress": "507,sun gravitas ,Ahmedabad",
            "shipToCountry": "India",
            "shipToState": "Dadra and Nagar Haveli",
            "shipToCity": "Silvassa",
            "shipToPincode": "564651",
            "shipTogstNumber": "",
            "transportId": None,
            "transportMode": None,
            "vehicleNo": "",
            "narration": "",
            "lrNo": "",
            "lrDate": "",
            "dueDays": None,
            "dueDate": "",
            "portOfLoading": None,
            "portOfDischarge": None,
            "shippingBillNo": None,
            "shippingDate": None,
            "portCode": None,
            "currencyCode": "INR",
            "currencyRate": "1",
            "taxableAmount": "1111",
            "igstLedgerId": 3,
            "igstAmount": "0",
            "cgstLedgerId": 7,
            "cgstAmount": "0",
            "sgstLedgerId": 5,
            "sgstAmount": "0",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "1111",
            "taxability": "EXEMPT",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "",
            "attachment": None,
            "reference": None,
            "outstanding": "1111",
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-07-15T09:14:42.986Z",
            "createBy": 2,
            "updateAt": "2025-07-15T09:14:42.986Z",
            "updateBy": 0,
            "items": [
                {
                    "id": 13,
                    "salesId": 14,
                    "invoiceDate": "2025-07-10T00:00:00.000Z",
                    "taxableType": "NILL",
                    "itemId": 1,
                    "warehouseId": None,
                    "batchNo": None,
                    "hsn": None,
                    "altUom": "LTR",
                    "altQty": 1,
                    "uom": "LTR",
                    "qty": 1,
                    "remainQty": 0,
                    "rateType": None,
                    "rate": "1111",
                    "total": "1111",
                    "igst": "0",
                    "igstAmount": "0",
                    "sgst": "0",
                    "sgstAmount": "0",
                    "cgst": "0",
                    "cgstAmount": "0",
                    "cess": "0",
                    "cessAmount": "0",
                    "discount": "0",
                    "discountAmount": "0",
                    "discountType": "PERCENTAGE",
                    "isInvoiceDiscount": False,
                    "invoiceDiscount": "100",
                    "invoiceDiscountAmount": "0",
                    "taxableAmount": "1111",
                    "remark": "",
                    "deliveryNoteId": None,
                    "isExpense": False,
                    "isAdditional": False,
                    "isCancel": False,
                    "isDelete": False,
                    "createAt": "2025-07-15T09:14:42.991Z",
                    "createBy": 2,
                    "updateAt": "2025-07-15T09:14:42.991Z",
                    "updateBy": 0
                }
            ],
            "eWayBill": [],
            "eInvoice": []
        },
        {
            "id": 12,
            "invoiceType": "ACCOUNT",
            "voucherId": 1,
            "invoiceNo": "SL-2",
            "invoiceDate": "27-06-2025",
            "ledgerId": None,
            "billToId": 17,
            "billToName": "Account",
            "billToAddress": "507,sun gravitas ,Ahmedabad",
            "billToCountry": "India",
            "billToState": "Dadra and Nagar Haveli",
            "billToCity": "Silvassa",
            "billToPincode": "564651",
            "billTogstNumber": None,
            "brokerId": None,
            "brokerage": None,
            "shipToId": 17,
            "shipToName": "Account",
            "shipToAddress": "507,sun gravitas ,Ahmedabad",
            "shipToCountry": "India",
            "shipToState": "Dadra and Nagar Haveli",
            "shipToCity": "Silvassa",
            "shipToPincode": "564651",
            "shipTogstNumber": "",
            "transportId": None,
            "transportMode": None,
            "vehicleNo": "",
            "narration": "",
            "lrNo": "",
            "lrDate": "",
            "dueDays": None,
            "dueDate": "",
            "portOfLoading": None,
            "portOfDischarge": None,
            "shippingBillNo": None,
            "shippingDate": None,
            "portCode": None,
            "currencyCode": "INR",
            "currencyRate": "11",
            "taxableAmount": "1",
            "igstLedgerId": 3,
            "igstAmount": "0",
            "cgstLedgerId": 7,
            "cgstAmount": "0",
            "sgstLedgerId": 5,
            "sgstAmount": "0",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "1",
            "taxability": "EXEMPT",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "<p>30 days credit</p>",
            "attachment": None,
            "reference": None,
            "outstanding": "11",
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-07-10T06:06:12.181Z",
            "createBy": 1,
            "updateAt": "2025-07-10T06:08:07.199Z",
            "updateBy": 1,
            "items": [],
            "eWayBill": [],
            "eInvoice": []
        },
        {
            "id": 7,
            "invoiceType": "ITEM",
            "voucherId": 1,
            "invoiceNo": "SL-1",
            "invoiceDate": "10-07-2025",
            "ledgerId": 15,
            "billToId": 18,
            "billToName": "Account",
            "billToAddress": "507,sun gravitas ,Ahmedabad",
            "billToCountry": "India",
            "billToState": "Dadra and Nagar Haveli",
            "billToCity": "Silvassa",
            "billToPincode": "564651",
            "billTogstNumber": None,
            "brokerId": None,
            "brokerage": None,
            "shipToId": 18,
            "shipToName": "Account",
            "shipToAddress": "507,sun gravitas ,Ahmedabad",
            "shipToCountry": "India",
            "shipToState": "Dadra and Nagar Haveli",
            "shipToCity": "Silvassa",
            "shipToPincode": "564651",
            "shipTogstNumber": "",
            "transportId": None,
            "transportMode": None,
            "vehicleNo": "",
            "narration": "",
            "lrNo": "",
            "lrDate": "",
            "dueDays": None,
            "dueDate": "",
            "portOfLoading": None,
            "portOfDischarge": None,
            "shippingBillNo": None,
            "shippingDate": None,
            "portCode": None,
            "currencyCode": "INR",
            "currencyRate": "1",
            "taxableAmount": "1111",
            "igstLedgerId": 3,
            "igstAmount": "0",
            "cgstLedgerId": 7,
            "cgstAmount": "0",
            "sgstLedgerId": 5,
            "sgstAmount": "0",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "1111",
            "taxability": "EXEMPT",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "",
            "attachment": None,
            "reference": None,
            "outstanding": "1111",
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-07-10T05:45:30.351Z",
            "createBy": 1,
            "updateAt": "2025-07-10T05:50:40.130Z",
            "updateBy": 1,
            "items": [],
            "eWayBill": [],
            "eInvoice": []
        },
        {
            "id": 1,
            "invoiceType": "ITEM",
            "voucherId": 1,
            "invoiceNo": "SL-1",
            "invoiceDate": "18-06-2024",
            "ledgerId": 15,
            "billToId": 17,
            "billToName": "rohan",
            "billToAddress": "sdfdsf",
            "billToCountry": "India",
            "billToState": "Bihar",
            "billToCity": "Asarganj",
            "billToPincode": "345545",
            "billTogstNumber": None,
            "brokerId": None,
            "brokerage": None,
            "shipToId": 17,
            "shipToName": "rohan",
            "shipToAddress": "regrgrfg",
            "shipToCountry": "India",
            "shipToState": "Bihar",
            "shipToCity": "Asarganj",
            "shipToPincode": "454545",
            "shipTogstNumber": "",
            "transportId": None,
            "transportMode": None,
            "vehicleNo": "",
            "narration": "",
            "lrNo": "",
            "lrDate": "18-06-2024",
            "dueDays": None,
            "dueDate": "",
            "portOfLoading": None,
            "portOfDischarge": None,
            "shippingBillNo": None,
            "shippingDate": None,
            "portCode": None,
            "currencyCode": "INR",
            "currencyRate": "1",
            "taxableAmount": "1000",
            "igstLedgerId": 3,
            "igstAmount": "120",
            "cgstLedgerId": 7,
            "cgstAmount": "60",
            "sgstLedgerId": 5,
            "sgstAmount": "60",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "1120",
            "taxability": "TAXABLE",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "",
            "attachment": None,
            "reference": None,
            "outstanding": "21119.99",
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-06-26T06:12:05.056Z",
            "createBy": 7,
            "updateAt": "2025-07-01T04:52:36.419Z",
            "updateBy": 0,
            "items": [],
            "eWayBill": [],
            "eInvoice": []
        }
    ],
    "total_rows": 4,
    "total_pages": 1
}
get_sale = sale
paym = {
    "st": True,
    "statusCode": 200,
    "data": [
        {
            "id": 9,
            "voucherId": 6,
            "invoiceNo": "PT-2",
            "accId": 20,
            "particularId": 17,
            "date": "23-06-2025",
            "amount": "10",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "",
            "referenceMode": "ONLINE",
            "referenceDate": "23-06-2025",
            "narration": "",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-14T10:43:56.124Z",
            "createBy": 2,
            "updateAt": "2025-07-14T10:43:56.124Z",
            "updateBy": 0,
            "account": {
                "id": 20,
                "name": "item"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 8,
            "voucherId": 6,
            "invoiceNo": "PT-1",
            "accId": 20,
            "particularId": 17,
            "date": "23-06-2025",
            "amount": "10",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "",
            "referenceMode": "ONLINE",
            "referenceDate": "23-06-2025",
            "narration": "",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-14T10:43:55.166Z",
            "createBy": 2,
            "updateAt": "2025-07-14T10:43:55.166Z",
            "updateBy": 0,
            "account": {
                "id": 20,
                "name": "item"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 7,
            "voucherId": 6,
            "invoiceNo": "PT-6",
            "accId": 20,
            "particularId": 17,
            "date": "13-06-2024",
            "amount": "10",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "",
            "referenceMode": "ONLINE",
            "referenceDate": "",
            "narration": "",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-14T10:42:57.121Z",
            "createBy": 2,
            "updateAt": "2025-07-14T10:42:57.121Z",
            "updateBy": 0,
            "account": {
                "id": 20,
                "name": "item"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 6,
            "voucherId": 6,
            "invoiceNo": "PT-5",
            "accId": 17,
            "particularId": 17,
            "date": "13-06-2024",
            "amount": "10",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "",
            "referenceMode": "ONLINE",
            "referenceDate": "13-06-2024",
            "narration": "",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-08T13:12:41.500Z",
            "createBy": 1,
            "updateAt": "2025-07-08T13:12:41.500Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 5,
            "voucherId": 6,
            "invoiceNo": "PT-4",
            "accId": 17,
            "particularId": 17,
            "date": "13-06-2024",
            "amount": "10",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "",
            "referenceMode": "ONLINE",
            "referenceDate": "13-06-2024",
            "narration": "",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-08T13:12:40.636Z",
            "createBy": 1,
            "updateAt": "2025-07-08T13:12:40.636Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 4,
            "voucherId": 6,
            "invoiceNo": "PT-3",
            "accId": 17,
            "particularId": 17,
            "date": "13-06-2024",
            "amount": "10",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "",
            "referenceMode": "ONLINE",
            "referenceDate": "13-06-2024",
            "narration": "",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-08T13:10:22.329Z",
            "createBy": 1,
            "updateAt": "2025-07-08T13:10:22.329Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 3,
            "voucherId": 6,
            "invoiceNo": "PT-2",
            "accId": 17,
            "particularId": 17,
            "date": "13-06-2024",
            "amount": "10",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "",
            "referenceMode": "ONLINE",
            "referenceDate": "",
            "narration": "",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-08T11:35:52.216Z",
            "createBy": 1,
            "updateAt": "2025-07-08T11:35:52.216Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 2,
            "voucherId": 6,
            "invoiceNo": "PT-1",
            "accId": 17,
            "particularId": 17,
            "date": "14-06-2024",
            "amount": "10",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "",
            "referenceMode": "ONLINE",
            "referenceDate": "",
            "narration": "",
            "attachment": "",
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-06-30T07:49:01.584Z",
            "createBy": 1,
            "updateAt": "2025-06-30T08:49:10.084Z",
            "updateBy": 1,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 1,
            "voucherId": 6,
            "invoiceNo": "PT-1",
            "accId": 17,
            "particularId": 3,
            "date": "23-06-2025",
            "amount": "10",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "",
            "referenceMode": "ONLINE",
            "referenceDate": "",
            "narration": "",
            "attachment": "",
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-06-28T12:39:53.586Z",
            "createBy": 7,
            "updateAt": "2025-07-14T10:52:29.678Z",
            "updateBy": 2,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 3,
                "name": "Output Igst"
            }
        }
    ],
    "total_rows": 9,
    "total_pages": 1
}
get_paym = paym
recp = {
    "st": True,
    "statusCode": 200,
    "data": [
        {
            "id": 15,
            "voucherId": 9,
            "invoiceNo": "SO-15",
            "accId": 17,
            "particularId": 17,
            "date": "30-06-2025",
            "amount": "20000",
            "methodAdjustmentType": "NewReference",
            "referenceNo": None,
            "referenceMode": "",
            "referenceDate": "30-06-2025",
            "narration": "sss",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-14T11:59:45.438Z",
            "createBy": 2,
            "updateAt": "2025-07-14T11:59:45.438Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 14,
            "voucherId": 9,
            "invoiceNo": "SO-14",
            "accId": 17,
            "particularId": 17,
            "date": "30-06-2025",
            "amount": "20000",
            "methodAdjustmentType": "NewReference",
            "referenceNo": None,
            "referenceMode": "",
            "referenceDate": "30-06-2025",
            "narration": "sss",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-09T05:55:49.993Z",
            "createBy": 1,
            "updateAt": "2025-07-09T05:55:49.993Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 13,
            "voucherId": 9,
            "invoiceNo": "SO-13",
            "accId": 17,
            "particularId": 17,
            "date": "30-06-2025",
            "amount": "20000",
            "methodAdjustmentType": "NewReference",
            "referenceNo": None,
            "referenceMode": "",
            "referenceDate": "30-06-2025",
            "narration": "sss",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-09T05:55:48.845Z",
            "createBy": 1,
            "updateAt": "2025-07-09T05:55:48.845Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 12,
            "voucherId": 9,
            "invoiceNo": "SO-12",
            "accId": 17,
            "particularId": 17,
            "date": "30-06-2025",
            "amount": "20000",
            "methodAdjustmentType": "NewReference",
            "referenceNo": None,
            "referenceMode": "CASH",
            "referenceDate": "30-06-2025",
            "narration": "sss",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-09T05:55:44.504Z",
            "createBy": 1,
            "updateAt": "2025-07-09T05:55:44.504Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 11,
            "voucherId": 9,
            "invoiceNo": "SO-11",
            "accId": 17,
            "particularId": 17,
            "date": "30-06-2025",
            "amount": "20000",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "eww",
            "referenceMode": "CASH",
            "referenceDate": "",
            "narration": "sss",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-09T05:52:47.830Z",
            "createBy": 1,
            "updateAt": "2025-07-09T05:52:47.830Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 10,
            "voucherId": 9,
            "invoiceNo": "SO-10",
            "accId": 17,
            "particularId": 17,
            "date": "30-06-2025",
            "amount": "20000",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "eww",
            "referenceMode": "CASH",
            "referenceDate": "01-07-2025",
            "narration": "sss",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-09T05:52:14.990Z",
            "createBy": 1,
            "updateAt": "2025-07-09T05:52:14.990Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 9,
            "voucherId": 9,
            "invoiceNo": "SO-9",
            "accId": 17,
            "particularId": 17,
            "date": "30-06-2025",
            "amount": "20",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "eww",
            "referenceMode": "CASH",
            "referenceDate": "01-07-2025",
            "narration": "sss",
            "attachment": None,
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-07-09T05:48:53.599Z",
            "createBy": 1,
            "updateAt": "2025-07-09T05:48:53.599Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 8,
            "voucherId": 9,
            "invoiceNo": "SO-8",
            "accId": 17,
            "particularId": 17,
            "date": "30-06-2025",
            "amount": "20",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "eww",
            "referenceMode": "CASH",
            "referenceDate": "01-07-2025",
            "narration": "sss",
            "attachment": "/attachment/30-5-2025/1751282769857.webp",
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-06-30T11:26:09.859Z",
            "createBy": 1,
            "updateAt": "2025-06-30T11:26:09.859Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 7,
            "voucherId": 9,
            "invoiceNo": "SO-7",
            "accId": 17,
            "particularId": 17,
            "date": "30-06-2025",
            "amount": "20000",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "eww",
            "referenceMode": "CASH",
            "referenceDate": "01-07-2025",
            "narration": "sss",
            "attachment": "/attachment/30-5-2025/1751282781315.webp",
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-06-30T06:24:26.183Z",
            "createBy": 7,
            "updateAt": "2025-07-14T12:02:22.112Z",
            "updateBy": 2,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        },
        {
            "id": 6,
            "voucherId": 9,
            "invoiceNo": "SO-6",
            "accId": 17,
            "particularId": 17,
            "date": "30-06-2025",
            "amount": "20",
            "methodAdjustmentType": "NewReference",
            "referenceNo": "eww",
            "referenceMode": "CASH",
            "referenceDate": "01-07-2025",
            "narration": "sss",
            "attachment": "/attachment/30-5-2025/1751264649543.webp",
            "reconciliation": None,
            "isDelete": False,
            "createAt": "2025-06-30T06:24:09.545Z",
            "createBy": 7,
            "updateAt": "2025-06-30T06:24:09.545Z",
            "updateBy": 0,
            "account": {
                "id": 17,
                "name": "rohan"
            },
            "particular": {
                "id": 17,
                "name": "rohan"
            }
        }
    ],
    "total_rows": 13,
    "total_pages": 2
}
get_recp = recp
sale_retrn = {
    "st": True,
    "statusCode": 200,
    "data": [
        {
            "id": 4,
            "invoiceType": "ITEM",
            "voucherId": 3,
            "invoiceNo": "CT-2",
            "invoiceDate": "10-07-2025",
            "ledgerId": 15,
            "billToId": 20,
            "billToName": "ABC Ltd",
            "billToAddress": "507,sun gravitas ,Ahmedabad",
            "billToCountry": "India",
            "billToState": "Andhra Pradesh",
            "billToCity": "Addanki",
            "billToPincode": "564651",
            "billTogstNumber": None,
            "shipToId": 20,
            "shipToName": "ABC Ltd",
            "shipToAddress": "507,sun gravitas ,Ahmedabad",
            "shipToCountry": "India",
            "shipToState": "Andhra Pradesh",
            "shipToCity": "Addanki",
            "shipToPincode": "564651",
            "shipTogstNumber": "",
            "transportId": None,
            "transportMode": None,
            "taxableAmount": "122221",
            "igstLedgerId": 3,
            "igstAmount": "0",
            "cgstLedgerId": 7,
            "cgstAmount": "0",
            "sgstLedgerId": 5,
            "sgstAmount": "0",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "122221",
            "taxability": "EXEMPT",
            "vehicleNo": "",
            "narration": "",
            "lrNo": "",
            "lrDate": "",
            "dueDays": 15,
            "dueDate": "2025-07-25T00:00:00.000Z",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "",
            "attachment": None,
            "reference": None,
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-07-15T10:58:48.313Z",
            "createBy": 2,
            "updateAt": "2025-07-15T10:59:43.030Z",
            "updateBy": 2,
            "items": []
        },
        {
            "id": 3,
            "invoiceType": "ITEM",
            "voucherId": 3,
            "invoiceNo": "CT-1",
            "invoiceDate": "10-07-2025",
            "ledgerId": 15,
            "billToId": 20,
            "billToName": "ABC Ltd",
            "billToAddress": "507,sun gravitas ,Ahmedabad",
            "billToCountry": "India",
            "billToState": "Andhra Pradesh",
            "billToCity": "Addanki",
            "billToPincode": "564651",
            "billTogstNumber": None,
            "shipToId": 20,
            "shipToName": "ABC Ltd",
            "shipToAddress": "507,sun gravitas ,Ahmedabad",
            "shipToCountry": "India",
            "shipToState": "Andhra Pradesh",
            "shipToCity": "Addanki",
            "shipToPincode": "564651",
            "shipTogstNumber": "",
            "transportId": None,
            "transportMode": None,
            "taxableAmount": "122221",
            "igstLedgerId": 3,
            "igstAmount": "0",
            "cgstLedgerId": 7,
            "cgstAmount": "0",
            "sgstLedgerId": 5,
            "sgstAmount": "0",
            "cessLedgerId": 11,
            "cessAmount": "0",
            "discountLedgerId": 12,
            "discountPercentage": "0",
            "discountAmount": "0",
            "discountType": "PERCENTAGE",
            "roundOffLedgerId": 13,
            "roundOffAmount": "0",
            "netAmount": "122221",
            "taxability": "EXEMPT",
            "vehicleNo": "",
            "narration": "",
            "lrNo": "",
            "lrDate": "",
            "dueDays": 15,
            "dueDate": "2025-07-25T00:00:00.000Z",
            "bankAccHolderName": None,
            "bankName": None,
            "branchName": None,
            "bankAccNo": None,
            "bankIfsc": None,
            "bankSwiftCode": None,
            "terms": "",
            "attachment": None,
            "reference": None,
            "isCancel": False,
            "isDelete": False,
            "createAt": "2025-07-10T07:22:25.774Z",
            "createBy": 1,
            "updateAt": "2025-07-10T07:26:59.979Z",
            "updateBy": 1,
            "items": []
        }
    ],
    "total_rows": 2,
    "total_pages": 1
}
get_sale_retrn = sale_retrn
hsn = {
    "st": True,
    "statusCode": 200,
    "data": [
        {
            "id": 3,
            "code": "pen0000111",
            "description": "wesgdgdfgdf",
            "igst": "18",
            "cgst": "9",
            "sgst": "9",
            "isDelete": False,
            "createAt": "2025-07-12T04:26:49.481Z",
            "createdBy": 2,
            "updateAt": "2025-07-12T04:42:14.106Z",
            "updateBy": 2
        },
        {
            "id": 2,
            "code": "pen00003",
            "description": "wesgdgdfgdf",
            "igst": "18",
            "cgst": "9",
            "sgst": "9",
            "isDelete": False,
            "createAt": "2025-07-02T13:09:46.145Z",
            "createdBy": 1,
            "updateAt": "2025-07-02T13:11:11.623Z",
            "updateBy": 1
        },
        {
            "id": 1,
            "code": "pen00001",
            "description": "wesgdgdfgdf",
            "igst": "18",
            "cgst": "9",
            "sgst": "9",
            "isDelete": False,
            "createAt": "2025-06-24T05:54:53.148Z",
            "createdBy": 7,
            "updateAt": "2025-06-24T05:54:53.148Z",
            "updateBy": 0
        }
    ],
    "total_rows": 3,
    "total_pages": 1
}
get_hsn = hsn